// Auto-generated. Do not edit!

// (in-package actionlib_tutorials.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CountToFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.currentNumber = null;
    }
    else {
      if (initObj.hasOwnProperty('currentNumber')) {
        this.currentNumber = initObj.currentNumber
      }
      else {
        this.currentNumber = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CountToFeedback
    // Serialize message field [currentNumber]
    bufferOffset = _serializer.int32(obj.currentNumber, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CountToFeedback
    let len;
    let data = new CountToFeedback(null);
    // Deserialize message field [currentNumber]
    data.currentNumber = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_tutorials/CountToFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '89d5afa92305bb7ac9f771f0a25145a9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int32 currentNumber
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CountToFeedback(null);
    if (msg.currentNumber !== undefined) {
      resolved.currentNumber = msg.currentNumber;
    }
    else {
      resolved.currentNumber = 0
    }

    return resolved;
    }
};

module.exports = CountToFeedback;
