// Auto-generated. Do not edit!

// (in-package actionlib_tutorials.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CountToGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goal_number = null;
    }
    else {
      if (initObj.hasOwnProperty('goal_number')) {
        this.goal_number = initObj.goal_number
      }
      else {
        this.goal_number = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CountToGoal
    // Serialize message field [goal_number]
    bufferOffset = _serializer.int32(obj.goal_number, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CountToGoal
    let len;
    let data = new CountToGoal(null);
    // Deserialize message field [goal_number]
    data.goal_number = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_tutorials/CountToGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '150721e4e07b176809c91593b29c06c1';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    int32 goal_number
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CountToGoal(null);
    if (msg.goal_number !== undefined) {
      resolved.goal_number = msg.goal_number;
    }
    else {
      resolved.goal_number = 0
    }

    return resolved;
    }
};

module.exports = CountToGoal;
