// Generated by gencpp from file actionlib_tutorials/CountToResult.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUTORIALS_MESSAGE_COUNTTORESULT_H
#define ACTIONLIB_TUTORIALS_MESSAGE_COUNTTORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_tutorials
{
template <class ContainerAllocator>
struct CountToResult_
{
  typedef CountToResult_<ContainerAllocator> Type;

  CountToResult_()
    : completionMessage()  {
    }
  CountToResult_(const ContainerAllocator& _alloc)
    : completionMessage(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _completionMessage_type;
  _completionMessage_type completionMessage;





  typedef boost::shared_ptr< ::actionlib_tutorials::CountToResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tutorials::CountToResult_<ContainerAllocator> const> ConstPtr;

}; // struct CountToResult_

typedef ::actionlib_tutorials::CountToResult_<std::allocator<void> > CountToResult;

typedef boost::shared_ptr< ::actionlib_tutorials::CountToResult > CountToResultPtr;
typedef boost::shared_ptr< ::actionlib_tutorials::CountToResult const> CountToResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_tutorials::CountToResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_tutorials::CountToResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actionlib_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'actionlib_tutorials': ['/home/dhruva/optimiseCosts/devel/share/actionlib_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::CountToResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::CountToResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::CountToResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::CountToResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::CountToResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::CountToResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tutorials::CountToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1d4055b52734c23312b7d360e5a377c";
  }

  static const char* value(const ::actionlib_tutorials::CountToResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1d4055b52734c23ULL;
  static const uint64_t static_value2 = 0x312b7d360e5a377cULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tutorials::CountToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_tutorials/CountToResult";
  }

  static const char* value(const ::actionlib_tutorials::CountToResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tutorials::CountToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
string completionMessage\n\
";
  }

  static const char* value(const ::actionlib_tutorials::CountToResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_tutorials::CountToResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.completionMessage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountToResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tutorials::CountToResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_tutorials::CountToResult_<ContainerAllocator>& v)
  {
    s << indent << "completionMessage: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.completionMessage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUTORIALS_MESSAGE_COUNTTORESULT_H
