; Auto-generated. Do not edit!


(cl:in-package actionlib_tutorials-msg)


;//! \htmlinclude CountToFeedback.msg.html

(cl:defclass <CountToFeedback> (roslisp-msg-protocol:ros-message)
  ((currentNumber
    :reader currentNumber
    :initarg :currentNumber
    :type cl:integer
    :initform 0))
)

(cl:defclass CountToFeedback (<CountToFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountToFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountToFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tutorials-msg:<CountToFeedback> is deprecated: use actionlib_tutorials-msg:CountToFeedback instead.")))

(cl:ensure-generic-function 'currentNumber-val :lambda-list '(m))
(cl:defmethod currentNumber-val ((m <CountToFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:currentNumber-val is deprecated.  Use actionlib_tutorials-msg:currentNumber instead.")
  (currentNumber m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountToFeedback>) ostream)
  "Serializes a message object of type '<CountToFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'currentNumber)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountToFeedback>) istream)
  "Deserializes a message object of type '<CountToFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'currentNumber) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountToFeedback>)))
  "Returns string type for a message object of type '<CountToFeedback>"
  "actionlib_tutorials/CountToFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountToFeedback)))
  "Returns string type for a message object of type 'CountToFeedback"
  "actionlib_tutorials/CountToFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountToFeedback>)))
  "Returns md5sum for a message object of type '<CountToFeedback>"
  "89d5afa92305bb7ac9f771f0a25145a9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountToFeedback)))
  "Returns md5sum for a message object of type 'CountToFeedback"
  "89d5afa92305bb7ac9f771f0a25145a9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountToFeedback>)))
  "Returns full string definition for message of type '<CountToFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 currentNumber~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountToFeedback)))
  "Returns full string definition for message of type 'CountToFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 currentNumber~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountToFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountToFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CountToFeedback
    (cl:cons ':currentNumber (currentNumber msg))
))
