; Auto-generated. Do not edit!


(cl:in-package actionlib_tutorials-msg)


;//! \htmlinclude CountToResult.msg.html

(cl:defclass <CountToResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass CountToResult (<CountToResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountToResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountToResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tutorials-msg:<CountToResult> is deprecated: use actionlib_tutorials-msg:CountToResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <CountToResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:result-val is deprecated.  Use actionlib_tutorials-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountToResult>) ostream)
  "Serializes a message object of type '<CountToResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountToResult>) istream)
  "Deserializes a message object of type '<CountToResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountToResult>)))
  "Returns string type for a message object of type '<CountToResult>"
  "actionlib_tutorials/CountToResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountToResult)))
  "Returns string type for a message object of type 'CountToResult"
  "actionlib_tutorials/CountToResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountToResult>)))
  "Returns md5sum for a message object of type '<CountToResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountToResult)))
  "Returns md5sum for a message object of type 'CountToResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountToResult>)))
  "Returns full string definition for message of type '<CountToResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountToResult)))
  "Returns full string definition for message of type 'CountToResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountToResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountToResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CountToResult
    (cl:cons ':result (result msg))
))
