; Auto-generated. Do not edit!


(cl:in-package actionlib_tutorials-msg)


;//! \htmlinclude CountToResult.msg.html

(cl:defclass <CountToResult> (roslisp-msg-protocol:ros-message)
  ((completionMessage
    :reader completionMessage
    :initarg :completionMessage
    :type cl:string
    :initform ""))
)

(cl:defclass CountToResult (<CountToResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountToResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountToResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tutorials-msg:<CountToResult> is deprecated: use actionlib_tutorials-msg:CountToResult instead.")))

(cl:ensure-generic-function 'completionMessage-val :lambda-list '(m))
(cl:defmethod completionMessage-val ((m <CountToResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:completionMessage-val is deprecated.  Use actionlib_tutorials-msg:completionMessage instead.")
  (completionMessage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountToResult>) ostream)
  "Serializes a message object of type '<CountToResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'completionMessage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'completionMessage))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountToResult>) istream)
  "Deserializes a message object of type '<CountToResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'completionMessage) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'completionMessage) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountToResult>)))
  "Returns string type for a message object of type '<CountToResult>"
  "actionlib_tutorials/CountToResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountToResult)))
  "Returns string type for a message object of type 'CountToResult"
  "actionlib_tutorials/CountToResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountToResult>)))
  "Returns md5sum for a message object of type '<CountToResult>"
  "f1d4055b52734c23312b7d360e5a377c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountToResult)))
  "Returns md5sum for a message object of type 'CountToResult"
  "f1d4055b52734c23312b7d360e5a377c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountToResult>)))
  "Returns full string definition for message of type '<CountToResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%string completionMessage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountToResult)))
  "Returns full string definition for message of type 'CountToResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%string completionMessage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountToResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'completionMessage))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountToResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CountToResult
    (cl:cons ':completionMessage (completionMessage msg))
))
